//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.customerattributes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for carrierName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="carrierName"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DX"/&gt;
 *     &lt;enumeration value="CollectPlus"/&gt;
 *     &lt;enumeration value="InPost"/&gt;
 *     &lt;enumeration value="Ups"/&gt;
 *     &lt;enumeration value="ClickAndQuick"/&gt;
 *     &lt;enumeration value="TNTExpressIT"/&gt;
 *     &lt;enumeration value="SPNPost"/&gt;
 *     &lt;enumeration value="Aramex"/&gt;
 *     &lt;enumeration value="UKMail"/&gt;
 *     &lt;enumeration value="DHLUK"/&gt;
 *     &lt;enumeration value="RicoUK"/&gt;
 *     &lt;enumeration value="RoyalMailUK"/&gt;
 *     &lt;enumeration value="CitySprintUK"/&gt;
 *     &lt;enumeration value="FedExUK"/&gt;
 *     &lt;enumeration value="TNTExpressUK"/&gt;
 *     &lt;enumeration value="APCUK"/&gt;
 *     &lt;enumeration value="AJGUK"/&gt;
 *     &lt;enumeration value="Carrier1UK"/&gt;
 *     &lt;enumeration value="Carrier2UK"/&gt;
 *     &lt;enumeration value="RemovedCityLink"/&gt;
 *     &lt;enumeration value="Laundry"/&gt;
 *     &lt;enumeration value="P4DUK"/&gt;
 *     &lt;enumeration value="IBMRicoUK"/&gt;
 *     &lt;enumeration value="P2GUK"/&gt;
 *     &lt;enumeration value="HermesUK"/&gt;
 *     &lt;enumeration value="Carrier1"/&gt;
 *     &lt;enumeration value="Carrier2"/&gt;
 *     &lt;enumeration value="Carrier3"/&gt;
 *     &lt;enumeration value="Carrier4"/&gt;
 *     &lt;enumeration value="Carrier5"/&gt;
 *     &lt;enumeration value="Carrier6"/&gt;
 *     &lt;enumeration value="Carrier7"/&gt;
 *     &lt;enumeration value="Carrier8"/&gt;
 *     &lt;enumeration value="Carrier9"/&gt;
 *     &lt;enumeration value="Carrier10"/&gt;
 *     &lt;enumeration value="PostaSlovenije"/&gt;
 *     &lt;enumeration value="AusPost"/&gt;
 *     &lt;enumeration value="HermesIT"/&gt;
 *     &lt;enumeration value="Fridge"/&gt;
 *     &lt;enumeration value="InPostBrasil"/&gt;
 *     &lt;enumeration value="PosteItaliane"/&gt;
 *     &lt;enumeration value="MallCZ"/&gt;
 *     &lt;enumeration value="MallSK"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "carrierName")
@XmlEnum
public enum CarrierName {

    DX("DX"),
    @XmlEnumValue("CollectPlus")
    COLLECT_PLUS("CollectPlus"),
    @XmlEnumValue("InPost")
    IN_POST("InPost"),
    @XmlEnumValue("Ups")
    UPS("Ups"),
    @XmlEnumValue("ClickAndQuick")
    CLICK_AND_QUICK("ClickAndQuick"),
    @XmlEnumValue("TNTExpressIT")
    TNT_EXPRESS_IT("TNTExpressIT"),
    @XmlEnumValue("SPNPost")
    SPN_POST("SPNPost"),
    @XmlEnumValue("Aramex")
    ARAMEX("Aramex"),
    @XmlEnumValue("UKMail")
    UK_MAIL("UKMail"),
    DHLUK("DHLUK"),
    @XmlEnumValue("RicoUK")
    RICO_UK("RicoUK"),
    @XmlEnumValue("RoyalMailUK")
    ROYAL_MAIL_UK("RoyalMailUK"),
    @XmlEnumValue("CitySprintUK")
    CITY_SPRINT_UK("CitySprintUK"),
    @XmlEnumValue("FedExUK")
    FED_EX_UK("FedExUK"),
    @XmlEnumValue("TNTExpressUK")
    TNT_EXPRESS_UK("TNTExpressUK"),
    APCUK("APCUK"),
    AJGUK("AJGUK"),
    @XmlEnumValue("Carrier1UK")
    CARRIER_1_UK("Carrier1UK"),
    @XmlEnumValue("Carrier2UK")
    CARRIER_2_UK("Carrier2UK"),
    @XmlEnumValue("RemovedCityLink")
    REMOVED_CITY_LINK("RemovedCityLink"),
    @XmlEnumValue("Laundry")
    LAUNDRY("Laundry"),
    @XmlEnumValue("P4DUK")
    P_4_DUK("P4DUK"),
    @XmlEnumValue("IBMRicoUK")
    IBM_RICO_UK("IBMRicoUK"),
    @XmlEnumValue("P2GUK")
    P_2_GUK("P2GUK"),
    @XmlEnumValue("HermesUK")
    HERMES_UK("HermesUK"),
    @XmlEnumValue("Carrier1")
    CARRIER_1("Carrier1"),
    @XmlEnumValue("Carrier2")
    CARRIER_2("Carrier2"),
    @XmlEnumValue("Carrier3")
    CARRIER_3("Carrier3"),
    @XmlEnumValue("Carrier4")
    CARRIER_4("Carrier4"),
    @XmlEnumValue("Carrier5")
    CARRIER_5("Carrier5"),
    @XmlEnumValue("Carrier6")
    CARRIER_6("Carrier6"),
    @XmlEnumValue("Carrier7")
    CARRIER_7("Carrier7"),
    @XmlEnumValue("Carrier8")
    CARRIER_8("Carrier8"),
    @XmlEnumValue("Carrier9")
    CARRIER_9("Carrier9"),
    @XmlEnumValue("Carrier10")
    CARRIER_10("Carrier10"),
    @XmlEnumValue("PostaSlovenije")
    POSTA_SLOVENIJE("PostaSlovenije"),
    @XmlEnumValue("AusPost")
    AUS_POST("AusPost"),
    @XmlEnumValue("HermesIT")
    HERMES_IT("HermesIT"),
    @XmlEnumValue("Fridge")
    FRIDGE("Fridge"),
    @XmlEnumValue("InPostBrasil")
    IN_POST_BRASIL("InPostBrasil"),
    @XmlEnumValue("PosteItaliane")
    POSTE_ITALIANE("PosteItaliane"),
    @XmlEnumValue("MallCZ")
    MALL_CZ("MallCZ"),
    @XmlEnumValue("MallSK")
    MALL_SK("MallSK");
    private final String value;

    CarrierName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CarrierName fromValue(String v) {
        for (CarrierName c: CarrierName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
