//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.customerattributes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for dispatchOrderVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dispatchOrderVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dispatchOrderId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="dispatchOrderStatus" type="{http://www.inpost.com.pl/Services/}dispatchOrderStatus" minOccurs="0"/&gt;
 *         &lt;element name="dispatchDateFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="dispatchDateTo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="packCodes" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="chargeType" type="{http://www.inpost.com.pl/Services/}chargeType" minOccurs="0"/&gt;
 *         &lt;element name="dispatchPoint" type="{http://www.inpost.com.pl/Services/}dispatchPointVO" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dispatchOrderVO", propOrder = {
    "dispatchOrderId",
    "dispatchOrderStatus",
    "dispatchDateFrom",
    "dispatchDateTo",
    "reference",
    "comment",
    "packCodes",
    "creationDate",
    "chargeType",
    "dispatchPoint"
})
public class DispatchOrderVO {

    protected Long dispatchOrderId;
    @XmlSchemaType(name = "string")
    protected DispatchOrderStatus dispatchOrderStatus;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dispatchDateFrom;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dispatchDateTo;
    protected String reference;
    protected String comment;
    @XmlElement(nillable = true)
    protected List<String> packCodes;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlSchemaType(name = "string")
    protected ChargeType chargeType;
    protected DispatchPointVO dispatchPoint;

    /**
     * Gets the value of the dispatchOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDispatchOrderId() {
        return dispatchOrderId;
    }

    /**
     * Sets the value of the dispatchOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDispatchOrderId(Long value) {
        this.dispatchOrderId = value;
    }

    /**
     * Gets the value of the dispatchOrderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DispatchOrderStatus }
     *     
     */
    public DispatchOrderStatus getDispatchOrderStatus() {
        return dispatchOrderStatus;
    }

    /**
     * Sets the value of the dispatchOrderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispatchOrderStatus }
     *     
     */
    public void setDispatchOrderStatus(DispatchOrderStatus value) {
        this.dispatchOrderStatus = value;
    }

    /**
     * Gets the value of the dispatchDateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDispatchDateFrom() {
        return dispatchDateFrom;
    }

    /**
     * Sets the value of the dispatchDateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDispatchDateFrom(XMLGregorianCalendar value) {
        this.dispatchDateFrom = value;
    }

    /**
     * Gets the value of the dispatchDateTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDispatchDateTo() {
        return dispatchDateTo;
    }

    /**
     * Sets the value of the dispatchDateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDispatchDateTo(XMLGregorianCalendar value) {
        this.dispatchDateTo = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the packCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPackCodes() {
        if (packCodes == null) {
            packCodes = new ArrayList<String>();
        }
        return this.packCodes;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeType }
     *     
     */
    public ChargeType getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeType }
     *     
     */
    public void setChargeType(ChargeType value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the dispatchPoint property.
     * 
     * @return
     *     possible object is
     *     {@link DispatchPointVO }
     *     
     */
    public DispatchPointVO getDispatchPoint() {
        return dispatchPoint;
    }

    /**
     * Sets the value of the dispatchPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispatchPointVO }
     *     
     */
    public void setDispatchPoint(DispatchPointVO value) {
        this.dispatchPoint = value;
    }

}
