app:
  name: KAFKA_REDIS_PROFILE_SENDER
server:
  port: ${SERVER_PORT:8080}
kafka:
  autoResetConfig: ${KAFKA_PROPERTY_AUTO_OFFSET_RESET_CONFIG:earliest}
  bootstrapServers: ${KAFKA_REDIS_PROFILE_SENDER_GE_BOOTSTRAP_SERVERS:kafka01-t-b-01.easypack24.net:9092,kafka01-t-b-02.easypack24.net:9092,kafka01-t-b-03.easypack24.net:9092,kafka01-t-b-04.easypack24.net:9092}
  producer:
    enabled: ${MODE_CUSTOMER_PROFILE:false}
    topicName: ${CUSTOMER_PROFILE_SENDER_GE_TOPIC_NAME:test-imur-parcel-property_localv2}
    applicationId: ${CUSTOMER_PROFILE_SENDER_GE_APPLICATION_ID:kafka-redis-profile-sender-parcel}
    schemaRegistryUrl: ${PARCEL_PARCEL_PROFILE_SENDER_GE_SCHEMA_REGISTRY_URL:http://kafka01-t-schema-registry.easypack24.net}

