//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.parcelwsservice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for mobileParcelVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mobileParcelVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="parcelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="courierLogin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="boxMachineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="onDeliveryAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="paymentStatus" type="{http://services.szop.inpost.pl/}packPaymentStatus" minOccurs="0"/&gt;
 *         &lt;element name="receiverPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="senderPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="senderEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="size" type="{http://services.szop.inpost.pl/}deliveryPackType" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://services.szop.inpost.pl/}packStatus" minOccurs="0"/&gt;
 *         &lt;element name="assignationStatus" type="{http://services.szop.inpost.pl/}assignationStatus" minOccurs="0"/&gt;
 *         &lt;element name="lastAssignationStatusChangeData" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mobileParcelVO", propOrder = {
    "parcelCode",
    "courierLogin",
    "boxMachineName",
    "onDeliveryAmount",
    "paymentStatus",
    "receiverPhoneNumber",
    "receiverEmail",
    "senderPhoneNumber",
    "senderEmail",
    "size",
    "status",
    "assignationStatus",
    "lastAssignationStatusChangeData"
})
public class MobileParcelVO {

    protected String parcelCode;
    protected String courierLogin;
    protected String boxMachineName;
    protected BigDecimal onDeliveryAmount;
    @XmlSchemaType(name = "string")
    protected PackPaymentStatus paymentStatus;
    protected String receiverPhoneNumber;
    protected String receiverEmail;
    protected String senderPhoneNumber;
    protected String senderEmail;
    @XmlSchemaType(name = "string")
    protected DeliveryPackType size;
    @XmlSchemaType(name = "string")
    protected PackStatus status;
    @XmlSchemaType(name = "string")
    protected AssignationStatus assignationStatus;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastAssignationStatusChangeData;

    /**
     * Gets the value of the parcelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParcelCode() {
        return parcelCode;
    }

    /**
     * Sets the value of the parcelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParcelCode(String value) {
        this.parcelCode = value;
    }

    /**
     * Gets the value of the courierLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourierLogin() {
        return courierLogin;
    }

    /**
     * Sets the value of the courierLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourierLogin(String value) {
        this.courierLogin = value;
    }

    /**
     * Gets the value of the boxMachineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoxMachineName() {
        return boxMachineName;
    }

    /**
     * Sets the value of the boxMachineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoxMachineName(String value) {
        this.boxMachineName = value;
    }

    /**
     * Gets the value of the onDeliveryAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOnDeliveryAmount() {
        return onDeliveryAmount;
    }

    /**
     * Sets the value of the onDeliveryAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOnDeliveryAmount(BigDecimal value) {
        this.onDeliveryAmount = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PackPaymentStatus }
     *     
     */
    public PackPaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackPaymentStatus }
     *     
     */
    public void setPaymentStatus(PackPaymentStatus value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the receiverPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverPhoneNumber() {
        return receiverPhoneNumber;
    }

    /**
     * Sets the value of the receiverPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverPhoneNumber(String value) {
        this.receiverPhoneNumber = value;
    }

    /**
     * Gets the value of the receiverEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverEmail() {
        return receiverEmail;
    }

    /**
     * Sets the value of the receiverEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverEmail(String value) {
        this.receiverEmail = value;
    }

    /**
     * Gets the value of the senderPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderPhoneNumber() {
        return senderPhoneNumber;
    }

    /**
     * Sets the value of the senderPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderPhoneNumber(String value) {
        this.senderPhoneNumber = value;
    }

    /**
     * Gets the value of the senderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderEmail(String value) {
        this.senderEmail = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryPackType }
     *     
     */
    public DeliveryPackType getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryPackType }
     *     
     */
    public void setSize(DeliveryPackType value) {
        this.size = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link PackStatus }
     *     
     */
    public PackStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackStatus }
     *     
     */
    public void setStatus(PackStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the assignationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link AssignationStatus }
     *     
     */
    public AssignationStatus getAssignationStatus() {
        return assignationStatus;
    }

    /**
     * Sets the value of the assignationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignationStatus }
     *     
     */
    public void setAssignationStatus(AssignationStatus value) {
        this.assignationStatus = value;
    }

    /**
     * Gets the value of the lastAssignationStatusChangeData property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastAssignationStatusChangeData() {
        return lastAssignationStatusChangeData;
    }

    /**
     * Sets the value of the lastAssignationStatusChangeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastAssignationStatusChangeData(XMLGregorianCalendar value) {
        this.lastAssignationStatusChangeData = value;
    }

}
