//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.parcelwsservice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for parcelPublicApiVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parcelPublicApiVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="status" type="{http://services.szop.inpost.pl/}packStatus" minOccurs="0"/&gt;
 *         &lt;element name="initialPackCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="statusChangeDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="preferredBoxMachineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="alternativeBoxMachineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="senderBoxMachineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customerReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parcelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="labelCreationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="customerDeliveringCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="confirmationPrinted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="labelPrinted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="paymentStatus" type="{http://services.szop.inpost.pl/}packPaymentStatus" minOccurs="0"/&gt;
 *         &lt;element name="size" type="{http://services.szop.inpost.pl/}deliveryPackType" minOccurs="0"/&gt;
 *         &lt;element name="calculatedChargedAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="amountCharged" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="insuranceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="onDeliveryAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="senderEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverCellNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverAddress" type="{http://services.szop.inpost.pl/}feAddressVO" minOccurs="0"/&gt;
 *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="carrierName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="carrierReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="serviceName" type="{http://services.szop.inpost.pl/}serviceName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parcelPublicApiVO", propOrder = {
    "status",
    "initialPackCode",
    "statusChangeDate",
    "preferredBoxMachineName",
    "alternativeBoxMachineName",
    "senderBoxMachineName",
    "customerReference",
    "parcelCode",
    "labelCreationDate",
    "creationDate",
    "customerDeliveringCode",
    "confirmationPrinted",
    "labelPrinted",
    "paymentStatus",
    "size",
    "calculatedChargedAmount",
    "amountCharged",
    "insuranceAmount",
    "onDeliveryAmount",
    "senderEmail",
    "receiverEmail",
    "receiverFirstName",
    "receiverLastName",
    "receiverPhoneNumber",
    "receiverCellNumber",
    "receiverAddress",
    "phoneNumber",
    "carrierName",
    "carrierReference",
    "serviceName"
})
public class ParcelPublicApiVO {

    @XmlSchemaType(name = "string")
    protected PackStatus status;
    protected String initialPackCode;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statusChangeDate;
    protected String preferredBoxMachineName;
    protected String alternativeBoxMachineName;
    protected String senderBoxMachineName;
    protected String customerReference;
    protected String parcelCode;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar labelCreationDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    protected int customerDeliveringCode;
    protected boolean confirmationPrinted;
    protected boolean labelPrinted;
    @XmlSchemaType(name = "string")
    protected PackPaymentStatus paymentStatus;
    @XmlSchemaType(name = "string")
    protected DeliveryPackType size;
    protected BigDecimal calculatedChargedAmount;
    protected BigDecimal amountCharged;
    protected BigDecimal insuranceAmount;
    protected BigDecimal onDeliveryAmount;
    protected String senderEmail;
    protected String receiverEmail;
    protected String receiverFirstName;
    protected String receiverLastName;
    protected String receiverPhoneNumber;
    protected String receiverCellNumber;
    protected FeAddressVO receiverAddress;
    protected String phoneNumber;
    protected String carrierName;
    protected String carrierReference;
    @XmlSchemaType(name = "string")
    protected ServiceName serviceName;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link PackStatus }
     *     
     */
    public PackStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackStatus }
     *     
     */
    public void setStatus(PackStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the initialPackCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialPackCode() {
        return initialPackCode;
    }

    /**
     * Sets the value of the initialPackCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialPackCode(String value) {
        this.initialPackCode = value;
    }

    /**
     * Gets the value of the statusChangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatusChangeDate() {
        return statusChangeDate;
    }

    /**
     * Sets the value of the statusChangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatusChangeDate(XMLGregorianCalendar value) {
        this.statusChangeDate = value;
    }

    /**
     * Gets the value of the preferredBoxMachineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredBoxMachineName() {
        return preferredBoxMachineName;
    }

    /**
     * Sets the value of the preferredBoxMachineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredBoxMachineName(String value) {
        this.preferredBoxMachineName = value;
    }

    /**
     * Gets the value of the alternativeBoxMachineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternativeBoxMachineName() {
        return alternativeBoxMachineName;
    }

    /**
     * Sets the value of the alternativeBoxMachineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternativeBoxMachineName(String value) {
        this.alternativeBoxMachineName = value;
    }

    /**
     * Gets the value of the senderBoxMachineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderBoxMachineName() {
        return senderBoxMachineName;
    }

    /**
     * Sets the value of the senderBoxMachineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderBoxMachineName(String value) {
        this.senderBoxMachineName = value;
    }

    /**
     * Gets the value of the customerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerReference() {
        return customerReference;
    }

    /**
     * Sets the value of the customerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerReference(String value) {
        this.customerReference = value;
    }

    /**
     * Gets the value of the parcelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParcelCode() {
        return parcelCode;
    }

    /**
     * Sets the value of the parcelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParcelCode(String value) {
        this.parcelCode = value;
    }

    /**
     * Gets the value of the labelCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLabelCreationDate() {
        return labelCreationDate;
    }

    /**
     * Sets the value of the labelCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLabelCreationDate(XMLGregorianCalendar value) {
        this.labelCreationDate = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the customerDeliveringCode property.
     * 
     */
    public int getCustomerDeliveringCode() {
        return customerDeliveringCode;
    }

    /**
     * Sets the value of the customerDeliveringCode property.
     * 
     */
    public void setCustomerDeliveringCode(int value) {
        this.customerDeliveringCode = value;
    }

    /**
     * Gets the value of the confirmationPrinted property.
     * 
     */
    public boolean isConfirmationPrinted() {
        return confirmationPrinted;
    }

    /**
     * Sets the value of the confirmationPrinted property.
     * 
     */
    public void setConfirmationPrinted(boolean value) {
        this.confirmationPrinted = value;
    }

    /**
     * Gets the value of the labelPrinted property.
     * 
     */
    public boolean isLabelPrinted() {
        return labelPrinted;
    }

    /**
     * Sets the value of the labelPrinted property.
     * 
     */
    public void setLabelPrinted(boolean value) {
        this.labelPrinted = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PackPaymentStatus }
     *     
     */
    public PackPaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackPaymentStatus }
     *     
     */
    public void setPaymentStatus(PackPaymentStatus value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryPackType }
     *     
     */
    public DeliveryPackType getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryPackType }
     *     
     */
    public void setSize(DeliveryPackType value) {
        this.size = value;
    }

    /**
     * Gets the value of the calculatedChargedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCalculatedChargedAmount() {
        return calculatedChargedAmount;
    }

    /**
     * Sets the value of the calculatedChargedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCalculatedChargedAmount(BigDecimal value) {
        this.calculatedChargedAmount = value;
    }

    /**
     * Gets the value of the amountCharged property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountCharged() {
        return amountCharged;
    }

    /**
     * Sets the value of the amountCharged property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountCharged(BigDecimal value) {
        this.amountCharged = value;
    }

    /**
     * Gets the value of the insuranceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsuranceAmount() {
        return insuranceAmount;
    }

    /**
     * Sets the value of the insuranceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsuranceAmount(BigDecimal value) {
        this.insuranceAmount = value;
    }

    /**
     * Gets the value of the onDeliveryAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOnDeliveryAmount() {
        return onDeliveryAmount;
    }

    /**
     * Sets the value of the onDeliveryAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOnDeliveryAmount(BigDecimal value) {
        this.onDeliveryAmount = value;
    }

    /**
     * Gets the value of the senderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderEmail(String value) {
        this.senderEmail = value;
    }

    /**
     * Gets the value of the receiverEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverEmail() {
        return receiverEmail;
    }

    /**
     * Sets the value of the receiverEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverEmail(String value) {
        this.receiverEmail = value;
    }

    /**
     * Gets the value of the receiverFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverFirstName() {
        return receiverFirstName;
    }

    /**
     * Sets the value of the receiverFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverFirstName(String value) {
        this.receiverFirstName = value;
    }

    /**
     * Gets the value of the receiverLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverLastName() {
        return receiverLastName;
    }

    /**
     * Sets the value of the receiverLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverLastName(String value) {
        this.receiverLastName = value;
    }

    /**
     * Gets the value of the receiverPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverPhoneNumber() {
        return receiverPhoneNumber;
    }

    /**
     * Sets the value of the receiverPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverPhoneNumber(String value) {
        this.receiverPhoneNumber = value;
    }

    /**
     * Gets the value of the receiverCellNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverCellNumber() {
        return receiverCellNumber;
    }

    /**
     * Sets the value of the receiverCellNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverCellNumber(String value) {
        this.receiverCellNumber = value;
    }

    /**
     * Gets the value of the receiverAddress property.
     * 
     * @return
     *     possible object is
     *     {@link FeAddressVO }
     *     
     */
    public FeAddressVO getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * Sets the value of the receiverAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeAddressVO }
     *     
     */
    public void setReceiverAddress(FeAddressVO value) {
        this.receiverAddress = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the carrierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierName() {
        return carrierName;
    }

    /**
     * Sets the value of the carrierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierName(String value) {
        this.carrierName = value;
    }

    /**
     * Gets the value of the carrierReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierReference() {
        return carrierReference;
    }

    /**
     * Sets the value of the carrierReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierReference(String value) {
        this.carrierReference = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceName }
     *     
     */
    public ServiceName getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceName }
     *     
     */
    public void setServiceName(ServiceName value) {
        this.serviceName = value;
    }

}
