//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.parcelwsservice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parcelPricesVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parcelPricesVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tmpId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="calculatedChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="fuelChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="notificationChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="codChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="insuranceChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="calculatedChargeAmountNonCommission" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="serviceName" type="{http://services.szop.inpost.pl/}serviceName" minOccurs="0"/&gt;
 *         &lt;element name="benefitAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="endOfWeekCollectionAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parcelPricesVO", propOrder = {
    "tmpId",
    "calculatedChargeAmount",
    "fuelChargeAmount",
    "notificationChargeAmount",
    "codChargeAmount",
    "insuranceChargeAmount",
    "calculatedChargeAmountNonCommission",
    "serviceName",
    "benefitAvailable",
    "endOfWeekCollectionAmount"
})
public class ParcelPricesVO {

    protected Integer tmpId;
    protected BigDecimal calculatedChargeAmount;
    protected BigDecimal fuelChargeAmount;
    protected BigDecimal notificationChargeAmount;
    protected BigDecimal codChargeAmount;
    protected BigDecimal insuranceChargeAmount;
    protected BigDecimal calculatedChargeAmountNonCommission;
    @XmlSchemaType(name = "string")
    protected ServiceName serviceName;
    protected boolean benefitAvailable;
    protected BigDecimal endOfWeekCollectionAmount;

    /**
     * Gets the value of the tmpId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTmpId() {
        return tmpId;
    }

    /**
     * Sets the value of the tmpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTmpId(Integer value) {
        this.tmpId = value;
    }

    /**
     * Gets the value of the calculatedChargeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCalculatedChargeAmount() {
        return calculatedChargeAmount;
    }

    /**
     * Sets the value of the calculatedChargeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCalculatedChargeAmount(BigDecimal value) {
        this.calculatedChargeAmount = value;
    }

    /**
     * Gets the value of the fuelChargeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFuelChargeAmount() {
        return fuelChargeAmount;
    }

    /**
     * Sets the value of the fuelChargeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFuelChargeAmount(BigDecimal value) {
        this.fuelChargeAmount = value;
    }

    /**
     * Gets the value of the notificationChargeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNotificationChargeAmount() {
        return notificationChargeAmount;
    }

    /**
     * Sets the value of the notificationChargeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNotificationChargeAmount(BigDecimal value) {
        this.notificationChargeAmount = value;
    }

    /**
     * Gets the value of the codChargeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCodChargeAmount() {
        return codChargeAmount;
    }

    /**
     * Sets the value of the codChargeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCodChargeAmount(BigDecimal value) {
        this.codChargeAmount = value;
    }

    /**
     * Gets the value of the insuranceChargeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsuranceChargeAmount() {
        return insuranceChargeAmount;
    }

    /**
     * Sets the value of the insuranceChargeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsuranceChargeAmount(BigDecimal value) {
        this.insuranceChargeAmount = value;
    }

    /**
     * Gets the value of the calculatedChargeAmountNonCommission property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCalculatedChargeAmountNonCommission() {
        return calculatedChargeAmountNonCommission;
    }

    /**
     * Sets the value of the calculatedChargeAmountNonCommission property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCalculatedChargeAmountNonCommission(BigDecimal value) {
        this.calculatedChargeAmountNonCommission = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceName }
     *     
     */
    public ServiceName getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceName }
     *     
     */
    public void setServiceName(ServiceName value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the benefitAvailable property.
     * 
     */
    public boolean isBenefitAvailable() {
        return benefitAvailable;
    }

    /**
     * Sets the value of the benefitAvailable property.
     * 
     */
    public void setBenefitAvailable(boolean value) {
        this.benefitAvailable = value;
    }

    /**
     * Gets the value of the endOfWeekCollectionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndOfWeekCollectionAmount() {
        return endOfWeekCollectionAmount;
    }

    /**
     * Sets the value of the endOfWeekCollectionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndOfWeekCollectionAmount(BigDecimal value) {
        this.endOfWeekCollectionAmount = value;
    }

}
