//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.parcelwsservice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for printoutFormats.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="printoutFormats"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Pdf"/&gt;
 *     &lt;enumeration value="Html"/&gt;
 *     &lt;enumeration value="Rtf"/&gt;
 *     &lt;enumeration value="Xml"/&gt;
 *     &lt;enumeration value="Epl2"/&gt;
 *     &lt;enumeration value="Zpl"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "printoutFormats")
@XmlEnum
public enum PrintoutFormats {

    @XmlEnumValue("Pdf")
    PDF("Pdf"),
    @XmlEnumValue("Html")
    HTML("Html"),
    @XmlEnumValue("Rtf")
    RTF("Rtf"),
    @XmlEnumValue("Xml")
    XML("Xml"),
    @XmlEnumValue("Epl2")
    EPL_2("Epl2"),
    @XmlEnumValue("Zpl")
    ZPL("Zpl");
    private final String value;

    PrintoutFormats(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrintoutFormats fromValue(String v) {
        for (PrintoutFormats c: PrintoutFormats.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
