//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.publicapi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for functionalityErrorSessionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="functionalityErrorSessionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Courier"/&gt;
 *     &lt;enumeration value="Customer"/&gt;
 *     &lt;enumeration value="Serviceman"/&gt;
 *     &lt;enumeration value="Escort"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "functionalityErrorSessionType")
@XmlEnum
public enum FunctionalityErrorSessionType {

    @XmlEnumValue("Courier")
    COURIER("Courier"),
    @XmlEnumValue("Customer")
    CUSTOMER("Customer"),
    @XmlEnumValue("Serviceman")
    SERVICEMAN("Serviceman"),
    @XmlEnumValue("Escort")
    ESCORT("Escort");
    private final String value;

    FunctionalityErrorSessionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FunctionalityErrorSessionType fromValue(String v) {
        for (FunctionalityErrorSessionType c: FunctionalityErrorSessionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
