//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.publicapi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getParcelsSimple complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getParcelsSimple"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dateRange" type="{http://services.szop.inpost.pl/}dateRangeVO" minOccurs="0"/&gt;
 *         &lt;element name="confirmationPrinted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="customerDelivering" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://services.szop.inpost.pl/}packStatus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="senderEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="senderPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receiverPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parcelCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="customerReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="preferredBoxMachineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="senderBoxMachineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fromAgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="toAgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="toOrFromAgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="carrier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="providerPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="providerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastStatusChangeDateRange" type="{http://services.szop.inpost.pl/}dateRangeVO" minOccurs="0"/&gt;
 *         &lt;element name="serviceName" type="{http://services.szop.inpost.pl/}serviceName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="carrierReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="claimRaised" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="excludeInitialParcelCode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="parcelCodeDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="senderExternalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endOfWeekCollection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="multiCompartmentPotentialUuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="multiCompartmentUuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pickupWithoutLabel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="temporaryParcelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="paging" type="{http://services.szop.inpost.pl/}pagingVO" minOccurs="0"/&gt;
 *         &lt;element name="sortField" type="{http://services.szop.inpost.pl/}parcelGetParcelsSortField" minOccurs="0"/&gt;
 *         &lt;element name="sortOrder" type="{http://services.szop.inpost.pl/}sortOrder" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getParcelsSimple", propOrder = {
    "dateRange",
    "confirmationPrinted",
    "customerDelivering",
    "status",
    "senderEmail",
    "senderPhoneNumber",
    "receiverEmail",
    "receiverPhoneNumber",
    "parcelCode",
    "customerReference",
    "preferredBoxMachineName",
    "senderBoxMachineName",
    "fromAgency",
    "toAgency",
    "toOrFromAgency",
    "carrier",
    "providerPhone",
    "providerName",
    "lastStatusChangeDateRange",
    "serviceName",
    "carrierReference",
    "claimRaised",
    "excludeInitialParcelCode",
    "parcelCodeDefinition",
    "senderExternalId",
    "endOfWeekCollection",
    "multiCompartmentPotentialUuid",
    "multiCompartmentUuid",
    "pickupWithoutLabel",
    "temporaryParcelCode",
    "paging",
    "sortField",
    "sortOrder"
})
public class GetParcelsSimple {

    protected DateRangeVO dateRange;
    protected Boolean confirmationPrinted;
    protected Boolean customerDelivering;
    @XmlSchemaType(name = "string")
    protected List<PackStatus> status;
    protected String senderEmail;
    protected String senderPhoneNumber;
    protected String receiverEmail;
    protected String receiverPhoneNumber;
    protected List<String> parcelCode;
    protected String customerReference;
    protected String preferredBoxMachineName;
    protected String senderBoxMachineName;
    protected String fromAgency;
    protected String toAgency;
    protected String toOrFromAgency;
    protected String carrier;
    protected String providerPhone;
    protected String providerName;
    protected DateRangeVO lastStatusChangeDateRange;
    @XmlSchemaType(name = "string")
    protected List<ServiceName> serviceName;
    protected String carrierReference;
    protected Boolean claimRaised;
    protected Boolean excludeInitialParcelCode;
    protected String parcelCodeDefinition;
    protected String senderExternalId;
    protected Boolean endOfWeekCollection;
    protected String multiCompartmentPotentialUuid;
    protected String multiCompartmentUuid;
    protected Boolean pickupWithoutLabel;
    protected String temporaryParcelCode;
    protected PagingVO paging;
    @XmlSchemaType(name = "string")
    protected ParcelGetParcelsSortField sortField;
    @XmlSchemaType(name = "string")
    protected SortOrder sortOrder;

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeVO }
     *     
     */
    public DateRangeVO getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeVO }
     *     
     */
    public void setDateRange(DateRangeVO value) {
        this.dateRange = value;
    }

    /**
     * Gets the value of the confirmationPrinted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isConfirmationPrinted() {
        return confirmationPrinted;
    }

    /**
     * Sets the value of the confirmationPrinted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConfirmationPrinted(Boolean value) {
        this.confirmationPrinted = value;
    }

    /**
     * Gets the value of the customerDelivering property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomerDelivering() {
        return customerDelivering;
    }

    /**
     * Sets the value of the customerDelivering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomerDelivering(Boolean value) {
        this.customerDelivering = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the status property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackStatus }
     * 
     * 
     */
    public List<PackStatus> getStatus() {
        if (status == null) {
            status = new ArrayList<PackStatus>();
        }
        return this.status;
    }

    /**
     * Gets the value of the senderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderEmail(String value) {
        this.senderEmail = value;
    }

    /**
     * Gets the value of the senderPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderPhoneNumber() {
        return senderPhoneNumber;
    }

    /**
     * Sets the value of the senderPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderPhoneNumber(String value) {
        this.senderPhoneNumber = value;
    }

    /**
     * Gets the value of the receiverEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverEmail() {
        return receiverEmail;
    }

    /**
     * Sets the value of the receiverEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverEmail(String value) {
        this.receiverEmail = value;
    }

    /**
     * Gets the value of the receiverPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverPhoneNumber() {
        return receiverPhoneNumber;
    }

    /**
     * Sets the value of the receiverPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverPhoneNumber(String value) {
        this.receiverPhoneNumber = value;
    }

    /**
     * Gets the value of the parcelCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parcelCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParcelCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getParcelCode() {
        if (parcelCode == null) {
            parcelCode = new ArrayList<String>();
        }
        return this.parcelCode;
    }

    /**
     * Gets the value of the customerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerReference() {
        return customerReference;
    }

    /**
     * Sets the value of the customerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerReference(String value) {
        this.customerReference = value;
    }

    /**
     * Gets the value of the preferredBoxMachineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredBoxMachineName() {
        return preferredBoxMachineName;
    }

    /**
     * Sets the value of the preferredBoxMachineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredBoxMachineName(String value) {
        this.preferredBoxMachineName = value;
    }

    /**
     * Gets the value of the senderBoxMachineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderBoxMachineName() {
        return senderBoxMachineName;
    }

    /**
     * Sets the value of the senderBoxMachineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderBoxMachineName(String value) {
        this.senderBoxMachineName = value;
    }

    /**
     * Gets the value of the fromAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromAgency() {
        return fromAgency;
    }

    /**
     * Sets the value of the fromAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromAgency(String value) {
        this.fromAgency = value;
    }

    /**
     * Gets the value of the toAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToAgency() {
        return toAgency;
    }

    /**
     * Sets the value of the toAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToAgency(String value) {
        this.toAgency = value;
    }

    /**
     * Gets the value of the toOrFromAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToOrFromAgency() {
        return toOrFromAgency;
    }

    /**
     * Sets the value of the toOrFromAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToOrFromAgency(String value) {
        this.toOrFromAgency = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier(String value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the providerPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderPhone() {
        return providerPhone;
    }

    /**
     * Sets the value of the providerPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderPhone(String value) {
        this.providerPhone = value;
    }

    /**
     * Gets the value of the providerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    /**
     * Gets the value of the lastStatusChangeDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeVO }
     *     
     */
    public DateRangeVO getLastStatusChangeDateRange() {
        return lastStatusChangeDateRange;
    }

    /**
     * Sets the value of the lastStatusChangeDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeVO }
     *     
     */
    public void setLastStatusChangeDateRange(DateRangeVO value) {
        this.lastStatusChangeDateRange = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceName }
     * 
     * 
     */
    public List<ServiceName> getServiceName() {
        if (serviceName == null) {
            serviceName = new ArrayList<ServiceName>();
        }
        return this.serviceName;
    }

    /**
     * Gets the value of the carrierReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierReference() {
        return carrierReference;
    }

    /**
     * Sets the value of the carrierReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierReference(String value) {
        this.carrierReference = value;
    }

    /**
     * Gets the value of the claimRaised property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClaimRaised() {
        return claimRaised;
    }

    /**
     * Sets the value of the claimRaised property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClaimRaised(Boolean value) {
        this.claimRaised = value;
    }

    /**
     * Gets the value of the excludeInitialParcelCode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExcludeInitialParcelCode() {
        return excludeInitialParcelCode;
    }

    /**
     * Sets the value of the excludeInitialParcelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcludeInitialParcelCode(Boolean value) {
        this.excludeInitialParcelCode = value;
    }

    /**
     * Gets the value of the parcelCodeDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParcelCodeDefinition() {
        return parcelCodeDefinition;
    }

    /**
     * Sets the value of the parcelCodeDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParcelCodeDefinition(String value) {
        this.parcelCodeDefinition = value;
    }

    /**
     * Gets the value of the senderExternalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderExternalId() {
        return senderExternalId;
    }

    /**
     * Sets the value of the senderExternalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderExternalId(String value) {
        this.senderExternalId = value;
    }

    /**
     * Gets the value of the endOfWeekCollection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEndOfWeekCollection() {
        return endOfWeekCollection;
    }

    /**
     * Sets the value of the endOfWeekCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEndOfWeekCollection(Boolean value) {
        this.endOfWeekCollection = value;
    }

    /**
     * Gets the value of the multiCompartmentPotentialUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiCompartmentPotentialUuid() {
        return multiCompartmentPotentialUuid;
    }

    /**
     * Sets the value of the multiCompartmentPotentialUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiCompartmentPotentialUuid(String value) {
        this.multiCompartmentPotentialUuid = value;
    }

    /**
     * Gets the value of the multiCompartmentUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiCompartmentUuid() {
        return multiCompartmentUuid;
    }

    /**
     * Sets the value of the multiCompartmentUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiCompartmentUuid(String value) {
        this.multiCompartmentUuid = value;
    }

    /**
     * Gets the value of the pickupWithoutLabel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPickupWithoutLabel() {
        return pickupWithoutLabel;
    }

    /**
     * Sets the value of the pickupWithoutLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPickupWithoutLabel(Boolean value) {
        this.pickupWithoutLabel = value;
    }

    /**
     * Gets the value of the temporaryParcelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporaryParcelCode() {
        return temporaryParcelCode;
    }

    /**
     * Sets the value of the temporaryParcelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporaryParcelCode(String value) {
        this.temporaryParcelCode = value;
    }

    /**
     * Gets the value of the paging property.
     * 
     * @return
     *     possible object is
     *     {@link PagingVO }
     *     
     */
    public PagingVO getPaging() {
        return paging;
    }

    /**
     * Sets the value of the paging property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagingVO }
     *     
     */
    public void setPaging(PagingVO value) {
        this.paging = value;
    }

    /**
     * Gets the value of the sortField property.
     * 
     * @return
     *     possible object is
     *     {@link ParcelGetParcelsSortField }
     *     
     */
    public ParcelGetParcelsSortField getSortField() {
        return sortField;
    }

    /**
     * Sets the value of the sortField property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParcelGetParcelsSortField }
     *     
     */
    public void setSortField(ParcelGetParcelsSortField value) {
        this.sortField = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link SortOrder }
     *     
     */
    public SortOrder getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortOrder }
     *     
     */
    public void setSortOrder(SortOrder value) {
        this.sortOrder = value;
    }

}
