//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.publicapi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for letterChannel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="letterChannel"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Allegro"/&gt;
 *     &lt;enumeration value="standard"/&gt;
 *     &lt;enumeration value="CrossBorder"/&gt;
 *     &lt;enumeration value="Cool"/&gt;
 *     &lt;enumeration value="ReverseReturn"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "letterChannel")
@XmlEnum
public enum LetterChannel {

    @XmlEnumValue("Allegro")
    ALLEGRO("Allegro"),
    @XmlEnumValue("standard")
    STANDARD("standard"),
    @XmlEnumValue("CrossBorder")
    CROSS_BORDER("CrossBorder"),
    @XmlEnumValue("Cool")
    COOL("Cool"),
    @XmlEnumValue("ReverseReturn")
    REVERSE_RETURN("ReverseReturn");
    private final String value;

    LetterChannel(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LetterChannel fromValue(String v) {
        for (LetterChannel c: LetterChannel.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
