//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.publicapi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for letterType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="letterType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="letter"/&gt;
 *     &lt;enumeration value="parcel"/&gt;
 *     &lt;enumeration value="courier"/&gt;
 *     &lt;enumeration value="parcelSmart"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "letterType")
@XmlEnum
public enum LetterType {

    @XmlEnumValue("letter")
    LETTER("letter"),
    @XmlEnumValue("parcel")
    PARCEL("parcel"),
    @XmlEnumValue("courier")
    COURIER("courier"),
    @XmlEnumValue("parcelSmart")
    PARCEL_SMART("parcelSmart");
    private final String value;

    LetterType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LetterType fromValue(String v) {
        for (LetterType c: LetterType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
