//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.publicapi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parcelAttributeName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="parcelAttributeName"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="customerCode"/&gt;
 *     &lt;enumeration value="customerTrackingId"/&gt;
 *     &lt;enumeration value="deliveryDepotNumber"/&gt;
 *     &lt;enumeration value="deliveryDepotName"/&gt;
 *     &lt;enumeration value="collectionDepotName"/&gt;
 *     &lt;enumeration value="deliveryDepotNumber2"/&gt;
 *     &lt;enumeration value="deliveryDepotNumber3"/&gt;
 *     &lt;enumeration value="deliveryDepotNumber4"/&gt;
 *     &lt;enumeration value="deliveryDepotNumber5"/&gt;
 *     &lt;enumeration value="deliveryDepotName2"/&gt;
 *     &lt;enumeration value="deliveryDepotName3"/&gt;
 *     &lt;enumeration value="deliveryDepotName4"/&gt;
 *     &lt;enumeration value="deliveryDepotName5"/&gt;
 *     &lt;enumeration value="deliveryOffset"/&gt;
 *     &lt;enumeration value="collectionOffset"/&gt;
 *     &lt;enumeration value="gazetteerVersion"/&gt;
 *     &lt;enumeration value="parcelCodeDefinition"/&gt;
 *     &lt;enumeration value="deliverArea"/&gt;
 *     &lt;enumeration value="collectionBarcode"/&gt;
 *     &lt;enumeration value="regeneratedCarrierReference"/&gt;
 *     &lt;enumeration value="serviceKey"/&gt;
 *     &lt;enumeration value="serviceKeyExpired"/&gt;
 *     &lt;enumeration value="serviceDescription"/&gt;
 *     &lt;enumeration value="orderNumber"/&gt;
 *     &lt;enumeration value="collectionDate"/&gt;
 *     &lt;enumeration value="collectionScheduled"/&gt;
 *     &lt;enumeration value="accountNumber"/&gt;
 *     &lt;enumeration value="receiptEmail"/&gt;
 *     &lt;enumeration value="benefitId"/&gt;
 *     &lt;enumeration value="originalSize"/&gt;
 *     &lt;enumeration value="value"/&gt;
 *     &lt;enumeration value="scannedWithTemporaryPrimaryBoxMachine"/&gt;
 *     &lt;enumeration value="scannedWithTemporarySenderBoxMachine"/&gt;
 *     &lt;enumeration value="removedDate"/&gt;
 *     &lt;enumeration value="claimEmail"/&gt;
 *     &lt;enumeration value="collectionDepotNumber"/&gt;
 *     &lt;enumeration value="routingConnection"/&gt;
 *     &lt;enumeration value="ChangeParcelSizeBoxMachineCourierDate"/&gt;
 *     &lt;enumeration value="ChangeParcelSizeBoxMachineCourierSizeBefore"/&gt;
 *     &lt;enumeration value="ChangeParcelSizeBoxMachineCourierSizeAfter"/&gt;
 *     &lt;enumeration value="ChangeParcelSizeBoxMachineSoftDate"/&gt;
 *     &lt;enumeration value="ChangeParcelSizeBoxMachineSoftSizeBefore"/&gt;
 *     &lt;enumeration value="ChangeParcelSizeBoxMachineSoftSizeAfter"/&gt;
 *     &lt;enumeration value="UnpaidParcelAutoPayment"/&gt;
 *     &lt;enumeration value="boxMachineBeforeStacking"/&gt;
 *     &lt;enumeration value="ChangeSizeProcess"/&gt;
 *     &lt;enumeration value="ChangeSizeDate"/&gt;
 *     &lt;enumeration value="AvailableSizes"/&gt;
 *     &lt;enumeration value="undeliveredParcelProcedure"/&gt;
 *     &lt;enumeration value="accountLegalStatus"/&gt;
 *     &lt;enumeration value="externalSenderId"/&gt;
 *     &lt;enumeration value="boxMachineZones"/&gt;
 *     &lt;enumeration value="originalReturnCode"/&gt;
 *     &lt;enumeration value="originalPayCode"/&gt;
 *     &lt;enumeration value="originalOpenCode"/&gt;
 *     &lt;enumeration value="waybillNumber"/&gt;
 *     &lt;enumeration value="weight"/&gt;
 *     &lt;enumeration value="initialPackCode"/&gt;
 *     &lt;enumeration value="channel"/&gt;
 *     &lt;enumeration value="customerReference"/&gt;
 *     &lt;enumeration value="providerName"/&gt;
 *     &lt;enumeration value="providerPhone"/&gt;
 *     &lt;enumeration value="receiverEmailOverride"/&gt;
 *     &lt;enumeration value="avizoParcel"/&gt;
 *     &lt;enumeration value="transactionId"/&gt;
 *     &lt;enumeration value="userId"/&gt;
 *     &lt;enumeration value="allegroReceiverLogin"/&gt;
 *     &lt;enumeration value="allegroSenderLogin"/&gt;
 *     &lt;enumeration value="declaredServiceName"/&gt;
 *     &lt;enumeration value="allegroActualReceiverEmail"/&gt;
 *     &lt;enumeration value="allegroOfferNumber"/&gt;
 *     &lt;enumeration value="originalServiceName"/&gt;
 *     &lt;enumeration value="parentServiceName"/&gt;
 *     &lt;enumeration value="taggedSMART"/&gt;
 *     &lt;enumeration value="StackingDenied"/&gt;
 *     &lt;enumeration value="receiverLanguage"/&gt;
 *     &lt;enumeration value="senderLanguage"/&gt;
 *     &lt;enumeration value="receiverSuppressNotifications"/&gt;
 *     &lt;enumeration value="senderSuppressNotifications"/&gt;
 *     &lt;enumeration value="originSystem"/&gt;
 *     &lt;enumeration value="parcelDescription"/&gt;
 *     &lt;enumeration value="originReceiverEmail"/&gt;
 *     &lt;enumeration value="originReceiverPhoneNum"/&gt;
 *     &lt;enumeration value="pickupCodeReSentCount"/&gt;
 *     &lt;enumeration value="codClearanceSenderBankAccount"/&gt;
 *     &lt;enumeration value="loyaltyCardNumber"/&gt;
 *     &lt;enumeration value="containerId"/&gt;
 *     &lt;enumeration value="containerType"/&gt;
 *     &lt;enumeration value="PISenderEmail"/&gt;
 *     &lt;enumeration value="collectionWithoutPhoneNumber"/&gt;
 *     &lt;enumeration value="PIReceiverEmail"/&gt;
 *     &lt;enumeration value="finalContainerType"/&gt;
 *     &lt;enumeration value="originalQuickSendCode"/&gt;
 *     &lt;enumeration value="multiCompartmentParcelCodeList"/&gt;
 *     &lt;enumeration value="multiCompartmentParcelList"/&gt;
 *     &lt;enumeration value="removedMultiCompartmentUuid"/&gt;
 *     &lt;enumeration value="removedMultiCompartmentSize"/&gt;
 *     &lt;enumeration value="removedMultiCompartmentPotentialUuid"/&gt;
 *     &lt;enumeration value="removedMultiCompartmentPotentialSize"/&gt;
 *     &lt;enumeration value="removedMultiCompartmentLead"/&gt;
 *     &lt;enumeration value="removedMultiCompartmentParcelCodeList"/&gt;
 *     &lt;enumeration value="removedMultiCompartmentParcelList"/&gt;
 *     &lt;enumeration value="multiCompartmentUnbindingDate"/&gt;
 *     &lt;enumeration value="multiCompartmentType"/&gt;
 *     &lt;enumeration value="originalAvizoTime"/&gt;
 *     &lt;enumeration value="originalExpirationTime"/&gt;
 *     &lt;enumeration value="multiCompartmentState"/&gt;
 *     &lt;enumeration value="removedMultiCompartmentState"/&gt;
 *     &lt;enumeration value="dduType"/&gt;
 *     &lt;enumeration value="pickupServices"/&gt;
 *     &lt;enumeration value="weightDeclaredForBilling"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "parcelAttributeName")
@XmlEnum
public enum ParcelAttributeName {

    @XmlEnumValue("customerCode")
    CUSTOMER_CODE("customerCode"),
    @XmlEnumValue("customerTrackingId")
    CUSTOMER_TRACKING_ID("customerTrackingId"),
    @XmlEnumValue("deliveryDepotNumber")
    DELIVERY_DEPOT_NUMBER("deliveryDepotNumber"),
    @XmlEnumValue("deliveryDepotName")
    DELIVERY_DEPOT_NAME("deliveryDepotName"),
    @XmlEnumValue("collectionDepotName")
    COLLECTION_DEPOT_NAME("collectionDepotName"),
    @XmlEnumValue("deliveryDepotNumber2")
    DELIVERY_DEPOT_NUMBER_2("deliveryDepotNumber2"),
    @XmlEnumValue("deliveryDepotNumber3")
    DELIVERY_DEPOT_NUMBER_3("deliveryDepotNumber3"),
    @XmlEnumValue("deliveryDepotNumber4")
    DELIVERY_DEPOT_NUMBER_4("deliveryDepotNumber4"),
    @XmlEnumValue("deliveryDepotNumber5")
    DELIVERY_DEPOT_NUMBER_5("deliveryDepotNumber5"),
    @XmlEnumValue("deliveryDepotName2")
    DELIVERY_DEPOT_NAME_2("deliveryDepotName2"),
    @XmlEnumValue("deliveryDepotName3")
    DELIVERY_DEPOT_NAME_3("deliveryDepotName3"),
    @XmlEnumValue("deliveryDepotName4")
    DELIVERY_DEPOT_NAME_4("deliveryDepotName4"),
    @XmlEnumValue("deliveryDepotName5")
    DELIVERY_DEPOT_NAME_5("deliveryDepotName5"),
    @XmlEnumValue("deliveryOffset")
    DELIVERY_OFFSET("deliveryOffset"),
    @XmlEnumValue("collectionOffset")
    COLLECTION_OFFSET("collectionOffset"),
    @XmlEnumValue("gazetteerVersion")
    GAZETTEER_VERSION("gazetteerVersion"),
    @XmlEnumValue("parcelCodeDefinition")
    PARCEL_CODE_DEFINITION("parcelCodeDefinition"),
    @XmlEnumValue("deliverArea")
    DELIVER_AREA("deliverArea"),
    @XmlEnumValue("collectionBarcode")
    COLLECTION_BARCODE("collectionBarcode"),
    @XmlEnumValue("regeneratedCarrierReference")
    REGENERATED_CARRIER_REFERENCE("regeneratedCarrierReference"),
    @XmlEnumValue("serviceKey")
    SERVICE_KEY("serviceKey"),
    @XmlEnumValue("serviceKeyExpired")
    SERVICE_KEY_EXPIRED("serviceKeyExpired"),
    @XmlEnumValue("serviceDescription")
    SERVICE_DESCRIPTION("serviceDescription"),
    @XmlEnumValue("orderNumber")
    ORDER_NUMBER("orderNumber"),
    @XmlEnumValue("collectionDate")
    COLLECTION_DATE("collectionDate"),
    @XmlEnumValue("collectionScheduled")
    COLLECTION_SCHEDULED("collectionScheduled"),
    @XmlEnumValue("accountNumber")
    ACCOUNT_NUMBER("accountNumber"),
    @XmlEnumValue("receiptEmail")
    RECEIPT_EMAIL("receiptEmail"),
    @XmlEnumValue("benefitId")
    BENEFIT_ID("benefitId"),
    @XmlEnumValue("originalSize")
    ORIGINAL_SIZE("originalSize"),
    @XmlEnumValue("value")
    VALUE("value"),
    @XmlEnumValue("scannedWithTemporaryPrimaryBoxMachine")
    SCANNED_WITH_TEMPORARY_PRIMARY_BOX_MACHINE("scannedWithTemporaryPrimaryBoxMachine"),
    @XmlEnumValue("scannedWithTemporarySenderBoxMachine")
    SCANNED_WITH_TEMPORARY_SENDER_BOX_MACHINE("scannedWithTemporarySenderBoxMachine"),
    @XmlEnumValue("removedDate")
    REMOVED_DATE("removedDate"),
    @XmlEnumValue("claimEmail")
    CLAIM_EMAIL("claimEmail"),
    @XmlEnumValue("collectionDepotNumber")
    COLLECTION_DEPOT_NUMBER("collectionDepotNumber"),
    @XmlEnumValue("routingConnection")
    ROUTING_CONNECTION("routingConnection"),
    @XmlEnumValue("ChangeParcelSizeBoxMachineCourierDate")
    CHANGE_PARCEL_SIZE_BOX_MACHINE_COURIER_DATE("ChangeParcelSizeBoxMachineCourierDate"),
    @XmlEnumValue("ChangeParcelSizeBoxMachineCourierSizeBefore")
    CHANGE_PARCEL_SIZE_BOX_MACHINE_COURIER_SIZE_BEFORE("ChangeParcelSizeBoxMachineCourierSizeBefore"),
    @XmlEnumValue("ChangeParcelSizeBoxMachineCourierSizeAfter")
    CHANGE_PARCEL_SIZE_BOX_MACHINE_COURIER_SIZE_AFTER("ChangeParcelSizeBoxMachineCourierSizeAfter"),
    @XmlEnumValue("ChangeParcelSizeBoxMachineSoftDate")
    CHANGE_PARCEL_SIZE_BOX_MACHINE_SOFT_DATE("ChangeParcelSizeBoxMachineSoftDate"),
    @XmlEnumValue("ChangeParcelSizeBoxMachineSoftSizeBefore")
    CHANGE_PARCEL_SIZE_BOX_MACHINE_SOFT_SIZE_BEFORE("ChangeParcelSizeBoxMachineSoftSizeBefore"),
    @XmlEnumValue("ChangeParcelSizeBoxMachineSoftSizeAfter")
    CHANGE_PARCEL_SIZE_BOX_MACHINE_SOFT_SIZE_AFTER("ChangeParcelSizeBoxMachineSoftSizeAfter"),
    @XmlEnumValue("UnpaidParcelAutoPayment")
    UNPAID_PARCEL_AUTO_PAYMENT("UnpaidParcelAutoPayment"),
    @XmlEnumValue("boxMachineBeforeStacking")
    BOX_MACHINE_BEFORE_STACKING("boxMachineBeforeStacking"),
    @XmlEnumValue("ChangeSizeProcess")
    CHANGE_SIZE_PROCESS("ChangeSizeProcess"),
    @XmlEnumValue("ChangeSizeDate")
    CHANGE_SIZE_DATE("ChangeSizeDate"),
    @XmlEnumValue("AvailableSizes")
    AVAILABLE_SIZES("AvailableSizes"),
    @XmlEnumValue("undeliveredParcelProcedure")
    UNDELIVERED_PARCEL_PROCEDURE("undeliveredParcelProcedure"),
    @XmlEnumValue("accountLegalStatus")
    ACCOUNT_LEGAL_STATUS("accountLegalStatus"),
    @XmlEnumValue("externalSenderId")
    EXTERNAL_SENDER_ID("externalSenderId"),
    @XmlEnumValue("boxMachineZones")
    BOX_MACHINE_ZONES("boxMachineZones"),
    @XmlEnumValue("originalReturnCode")
    ORIGINAL_RETURN_CODE("originalReturnCode"),
    @XmlEnumValue("originalPayCode")
    ORIGINAL_PAY_CODE("originalPayCode"),
    @XmlEnumValue("originalOpenCode")
    ORIGINAL_OPEN_CODE("originalOpenCode"),
    @XmlEnumValue("waybillNumber")
    WAYBILL_NUMBER("waybillNumber"),
    @XmlEnumValue("weight")
    WEIGHT("weight"),
    @XmlEnumValue("initialPackCode")
    INITIAL_PACK_CODE("initialPackCode"),
    @XmlEnumValue("channel")
    CHANNEL("channel"),
    @XmlEnumValue("customerReference")
    CUSTOMER_REFERENCE("customerReference"),
    @XmlEnumValue("providerName")
    PROVIDER_NAME("providerName"),
    @XmlEnumValue("providerPhone")
    PROVIDER_PHONE("providerPhone"),
    @XmlEnumValue("receiverEmailOverride")
    RECEIVER_EMAIL_OVERRIDE("receiverEmailOverride"),
    @XmlEnumValue("avizoParcel")
    AVIZO_PARCEL("avizoParcel"),
    @XmlEnumValue("transactionId")
    TRANSACTION_ID("transactionId"),
    @XmlEnumValue("userId")
    USER_ID("userId"),
    @XmlEnumValue("allegroReceiverLogin")
    ALLEGRO_RECEIVER_LOGIN("allegroReceiverLogin"),
    @XmlEnumValue("allegroSenderLogin")
    ALLEGRO_SENDER_LOGIN("allegroSenderLogin"),
    @XmlEnumValue("declaredServiceName")
    DECLARED_SERVICE_NAME("declaredServiceName"),
    @XmlEnumValue("allegroActualReceiverEmail")
    ALLEGRO_ACTUAL_RECEIVER_EMAIL("allegroActualReceiverEmail"),
    @XmlEnumValue("allegroOfferNumber")
    ALLEGRO_OFFER_NUMBER("allegroOfferNumber"),
    @XmlEnumValue("originalServiceName")
    ORIGINAL_SERVICE_NAME("originalServiceName"),
    @XmlEnumValue("parentServiceName")
    PARENT_SERVICE_NAME("parentServiceName"),
    @XmlEnumValue("taggedSMART")
    TAGGED_SMART("taggedSMART"),
    @XmlEnumValue("StackingDenied")
    STACKING_DENIED("StackingDenied"),
    @XmlEnumValue("receiverLanguage")
    RECEIVER_LANGUAGE("receiverLanguage"),
    @XmlEnumValue("senderLanguage")
    SENDER_LANGUAGE("senderLanguage"),
    @XmlEnumValue("receiverSuppressNotifications")
    RECEIVER_SUPPRESS_NOTIFICATIONS("receiverSuppressNotifications"),
    @XmlEnumValue("senderSuppressNotifications")
    SENDER_SUPPRESS_NOTIFICATIONS("senderSuppressNotifications"),
    @XmlEnumValue("originSystem")
    ORIGIN_SYSTEM("originSystem"),
    @XmlEnumValue("parcelDescription")
    PARCEL_DESCRIPTION("parcelDescription"),
    @XmlEnumValue("originReceiverEmail")
    ORIGIN_RECEIVER_EMAIL("originReceiverEmail"),
    @XmlEnumValue("originReceiverPhoneNum")
    ORIGIN_RECEIVER_PHONE_NUM("originReceiverPhoneNum"),
    @XmlEnumValue("pickupCodeReSentCount")
    PICKUP_CODE_RE_SENT_COUNT("pickupCodeReSentCount"),
    @XmlEnumValue("codClearanceSenderBankAccount")
    COD_CLEARANCE_SENDER_BANK_ACCOUNT("codClearanceSenderBankAccount"),
    @XmlEnumValue("loyaltyCardNumber")
    LOYALTY_CARD_NUMBER("loyaltyCardNumber"),
    @XmlEnumValue("containerId")
    CONTAINER_ID("containerId"),
    @XmlEnumValue("containerType")
    CONTAINER_TYPE("containerType"),
    @XmlEnumValue("PISenderEmail")
    PI_SENDER_EMAIL("PISenderEmail"),
    @XmlEnumValue("collectionWithoutPhoneNumber")
    COLLECTION_WITHOUT_PHONE_NUMBER("collectionWithoutPhoneNumber"),
    @XmlEnumValue("PIReceiverEmail")
    PI_RECEIVER_EMAIL("PIReceiverEmail"),
    @XmlEnumValue("finalContainerType")
    FINAL_CONTAINER_TYPE("finalContainerType"),
    @XmlEnumValue("originalQuickSendCode")
    ORIGINAL_QUICK_SEND_CODE("originalQuickSendCode"),
    @XmlEnumValue("multiCompartmentParcelCodeList")
    MULTI_COMPARTMENT_PARCEL_CODE_LIST("multiCompartmentParcelCodeList"),
    @XmlEnumValue("multiCompartmentParcelList")
    MULTI_COMPARTMENT_PARCEL_LIST("multiCompartmentParcelList"),
    @XmlEnumValue("removedMultiCompartmentUuid")
    REMOVED_MULTI_COMPARTMENT_UUID("removedMultiCompartmentUuid"),
    @XmlEnumValue("removedMultiCompartmentSize")
    REMOVED_MULTI_COMPARTMENT_SIZE("removedMultiCompartmentSize"),
    @XmlEnumValue("removedMultiCompartmentPotentialUuid")
    REMOVED_MULTI_COMPARTMENT_POTENTIAL_UUID("removedMultiCompartmentPotentialUuid"),
    @XmlEnumValue("removedMultiCompartmentPotentialSize")
    REMOVED_MULTI_COMPARTMENT_POTENTIAL_SIZE("removedMultiCompartmentPotentialSize"),
    @XmlEnumValue("removedMultiCompartmentLead")
    REMOVED_MULTI_COMPARTMENT_LEAD("removedMultiCompartmentLead"),
    @XmlEnumValue("removedMultiCompartmentParcelCodeList")
    REMOVED_MULTI_COMPARTMENT_PARCEL_CODE_LIST("removedMultiCompartmentParcelCodeList"),
    @XmlEnumValue("removedMultiCompartmentParcelList")
    REMOVED_MULTI_COMPARTMENT_PARCEL_LIST("removedMultiCompartmentParcelList"),
    @XmlEnumValue("multiCompartmentUnbindingDate")
    MULTI_COMPARTMENT_UNBINDING_DATE("multiCompartmentUnbindingDate"),
    @XmlEnumValue("multiCompartmentType")
    MULTI_COMPARTMENT_TYPE("multiCompartmentType"),
    @XmlEnumValue("originalAvizoTime")
    ORIGINAL_AVIZO_TIME("originalAvizoTime"),
    @XmlEnumValue("originalExpirationTime")
    ORIGINAL_EXPIRATION_TIME("originalExpirationTime"),
    @XmlEnumValue("multiCompartmentState")
    MULTI_COMPARTMENT_STATE("multiCompartmentState"),
    @XmlEnumValue("removedMultiCompartmentState")
    REMOVED_MULTI_COMPARTMENT_STATE("removedMultiCompartmentState"),
    @XmlEnumValue("dduType")
    DDU_TYPE("dduType"),
    @XmlEnumValue("pickupServices")
    PICKUP_SERVICES("pickupServices"),
    @XmlEnumValue("weightDeclaredForBilling")
    WEIGHT_DECLARED_FOR_BILLING("weightDeclaredForBilling");
    private final String value;

    ParcelAttributeName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParcelAttributeName fromValue(String v) {
        for (ParcelAttributeName c: ParcelAttributeName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
