//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:22 PM CEST 
//


package pl.inpost.szop.publicapi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for partner.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="partner"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="karTel"/&gt;
 *     &lt;enumeration value="test"/&gt;
 *     &lt;enumeration value="lotos"/&gt;
 *     &lt;enumeration value="pointPack"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "partner")
@XmlEnum
public enum Partner {

    @XmlEnumValue("karTel")
    KAR_TEL("karTel"),
    @XmlEnumValue("test")
    TEST("test"),
    @XmlEnumValue("lotos")
    LOTOS("lotos"),
    @XmlEnumValue("pointPack")
    POINT_PACK("pointPack");
    private final String value;

    Partner(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Partner fromValue(String v) {
        for (Partner c: Partner.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
