//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:21 PM CEST 
//


package pl.inpost.szop.customer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for apiMethodName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="apiMethodName"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CREATE_PARCELS"/&gt;
 *     &lt;enumeration value="PAY_FOR_PARCELS"/&gt;
 *     &lt;enumeration value="CANCEL_PARCEL"/&gt;
 *     &lt;enumeration value="CHANGE_PARCEL_SIZE"/&gt;
 *     &lt;enumeration value="GET_DISPATCH_ORDER_PRINTOUT"/&gt;
 *     &lt;enumeration value="GET_DISPATCH_ORDER_PRINTOUT_FOR_UNASSIGNED_PARCELS"/&gt;
 *     &lt;enumeration value="ACTIVATE_USER"/&gt;
 *     &lt;enumeration value="FIND_CUSTOMER"/&gt;
 *     &lt;enumeration value="UPDATE_CUSTOMER"/&gt;
 *     &lt;enumeration value="CREATE_CUSTOMER"/&gt;
 *     &lt;enumeration value="DELETE_CUSTOMER"/&gt;
 *     &lt;enumeration value="MANAGE_FUNDS"/&gt;
 *     &lt;enumeration value="SET_PASSWORD"/&gt;
 *     &lt;enumeration value="RESET_PASSWORD"/&gt;
 *     &lt;enumeration value="INITIALIZE_RESET_PASSWORD"/&gt;
 *     &lt;enumeration value="CHANGE_PASSWORD_WITH_TOKEN"/&gt;
 *     &lt;enumeration value="ASSIGN_BENEFIT_TO_CUSTOMER"/&gt;
 *     &lt;enumeration value="ADD_BENEFIT"/&gt;
 *     &lt;enumeration value="CANCEL_BENEFIT"/&gt;
 *     &lt;enumeration value="GET_BENEFITS"/&gt;
 *     &lt;enumeration value="GET_BENEFIT"/&gt;
 *     &lt;enumeration value="CREATE_NOT_ACTIVE_BENEFITS"/&gt;
 *     &lt;enumeration value="SET_CANCELED_BY_EXTERNAL_LOGISTIC"/&gt;
 *     &lt;enumeration value="SET_NOT_DELIVERED_BY_EXTERNAL_LOGISTIC"/&gt;
 *     &lt;enumeration value="SET_DELIVERED_TO_SORTING_CENTER_BY_EXTERNAL_LOGISTIC"/&gt;
 *     &lt;enumeration value="SET_RETURNED_TO_SORTING_CENTER_BY_EXTERNAL_LOGISTIC"/&gt;
 *     &lt;enumeration value="SET_DELIVERED_TO_AGENCY_BY_EXTERNAL_LOGISTIC"/&gt;
 *     &lt;enumeration value="SET_SENT_BY_EXTERNAL_LOGISTIC"/&gt;
 *     &lt;enumeration value="SET_RETURNED_TO_SENDER_BY_EXTERNAL_LOGISTIC"/&gt;
 *     &lt;enumeration value="FIND_BOX_MACHINES_BY_GEOLOCATION"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "apiMethodName")
@XmlEnum
public enum ApiMethodName {

    CREATE_PARCELS,
    PAY_FOR_PARCELS,
    CANCEL_PARCEL,
    CHANGE_PARCEL_SIZE,
    GET_DISPATCH_ORDER_PRINTOUT,
    GET_DISPATCH_ORDER_PRINTOUT_FOR_UNASSIGNED_PARCELS,
    ACTIVATE_USER,
    FIND_CUSTOMER,
    UPDATE_CUSTOMER,
    CREATE_CUSTOMER,
    DELETE_CUSTOMER,
    MANAGE_FUNDS,
    SET_PASSWORD,
    RESET_PASSWORD,
    INITIALIZE_RESET_PASSWORD,
    CHANGE_PASSWORD_WITH_TOKEN,
    ASSIGN_BENEFIT_TO_CUSTOMER,
    ADD_BENEFIT,
    CANCEL_BENEFIT,
    GET_BENEFITS,
    GET_BENEFIT,
    CREATE_NOT_ACTIVE_BENEFITS,
    SET_CANCELED_BY_EXTERNAL_LOGISTIC,
    SET_NOT_DELIVERED_BY_EXTERNAL_LOGISTIC,
    SET_DELIVERED_TO_SORTING_CENTER_BY_EXTERNAL_LOGISTIC,
    SET_RETURNED_TO_SORTING_CENTER_BY_EXTERNAL_LOGISTIC,
    SET_DELIVERED_TO_AGENCY_BY_EXTERNAL_LOGISTIC,
    SET_SENT_BY_EXTERNAL_LOGISTIC,
    SET_RETURNED_TO_SENDER_BY_EXTERNAL_LOGISTIC,
    FIND_BOX_MACHINES_BY_GEOLOCATION;

    public String value() {
        return name();
    }

    public static ApiMethodName fromValue(String v) {
        return valueOf(v);
    }

}
