//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:21 PM CEST 
//


package pl.inpost.szop.customer;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for codRaportRespons complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="codRaportRespons"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="amountWithoutCommision" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="boxMachineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comissionForCod" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dateOfParcelDelivered" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="kkm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parcelBarcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="priceForDelivery" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="receiptNumbers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="receivedCod" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "codRaportRespons", propOrder = {
    "amountWithoutCommision",
    "boxMachineName",
    "comissionForCod",
    "dateOfParcelDelivered",
    "id",
    "kkm",
    "parcelBarcode",
    "priceForDelivery",
    "receiptNumbers",
    "receivedCod"
})
public class CodRaportRespons {

    protected BigDecimal amountWithoutCommision;
    protected String boxMachineName;
    protected BigDecimal comissionForCod;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateOfParcelDelivered;
    protected long id;
    protected String kkm;
    protected String parcelBarcode;
    protected BigDecimal priceForDelivery;
    protected String receiptNumbers;
    protected BigDecimal receivedCod;

    /**
     * Gets the value of the amountWithoutCommision property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountWithoutCommision() {
        return amountWithoutCommision;
    }

    /**
     * Sets the value of the amountWithoutCommision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountWithoutCommision(BigDecimal value) {
        this.amountWithoutCommision = value;
    }

    /**
     * Gets the value of the boxMachineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoxMachineName() {
        return boxMachineName;
    }

    /**
     * Sets the value of the boxMachineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoxMachineName(String value) {
        this.boxMachineName = value;
    }

    /**
     * Gets the value of the comissionForCod property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getComissionForCod() {
        return comissionForCod;
    }

    /**
     * Sets the value of the comissionForCod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setComissionForCod(BigDecimal value) {
        this.comissionForCod = value;
    }

    /**
     * Gets the value of the dateOfParcelDelivered property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfParcelDelivered() {
        return dateOfParcelDelivered;
    }

    /**
     * Sets the value of the dateOfParcelDelivered property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfParcelDelivered(XMLGregorianCalendar value) {
        this.dateOfParcelDelivered = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the kkm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKkm() {
        return kkm;
    }

    /**
     * Sets the value of the kkm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKkm(String value) {
        this.kkm = value;
    }

    /**
     * Gets the value of the parcelBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParcelBarcode() {
        return parcelBarcode;
    }

    /**
     * Sets the value of the parcelBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParcelBarcode(String value) {
        this.parcelBarcode = value;
    }

    /**
     * Gets the value of the priceForDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceForDelivery() {
        return priceForDelivery;
    }

    /**
     * Sets the value of the priceForDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceForDelivery(BigDecimal value) {
        this.priceForDelivery = value;
    }

    /**
     * Gets the value of the receiptNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptNumbers() {
        return receiptNumbers;
    }

    /**
     * Sets the value of the receiptNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptNumbers(String value) {
        this.receiptNumbers = value;
    }

    /**
     * Gets the value of the receivedCod property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReceivedCod() {
        return receivedCod;
    }

    /**
     * Sets the value of the receivedCod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReceivedCod(BigDecimal value) {
        this.receivedCod = value;
    }

}
