//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:28:21 PM CEST 
//


package pl.inpost.szop.customer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reservationStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="reservationStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Approved"/&gt;
 *     &lt;enumeration value="Created"/&gt;
 *     &lt;enumeration value="Cancelled"/&gt;
 *     &lt;enumeration value="Changed"/&gt;
 *     &lt;enumeration value="Completed"/&gt;
 *     &lt;enumeration value="NotUsed"/&gt;
 *     &lt;enumeration value="Reminded"/&gt;
 *     &lt;enumeration value="Stored"/&gt;
 *     &lt;enumeration value="Used"/&gt;
 *     &lt;enumeration value="Returned"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "reservationStatus")
@XmlEnum
public enum ReservationStatus {

    @XmlEnumValue("Approved")
    APPROVED("Approved"),
    @XmlEnumValue("Created")
    CREATED("Created"),
    @XmlEnumValue("Cancelled")
    CANCELLED("Cancelled"),
    @XmlEnumValue("Changed")
    CHANGED("Changed"),
    @XmlEnumValue("Completed")
    COMPLETED("Completed"),
    @XmlEnumValue("NotUsed")
    NOT_USED("NotUsed"),
    @XmlEnumValue("Reminded")
    REMINDED("Reminded"),
    @XmlEnumValue("Stored")
    STORED("Stored"),
    @XmlEnumValue("Used")
    USED("Used"),
    @XmlEnumValue("Returned")
    RETURNED("Returned");
    private final String value;

    ReservationStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReservationStatus fromValue(String v) {
        for (ReservationStatus c: ReservationStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
